apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-api-chart.fullname" . }}
  labels:
    {{- include "devops-api-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "devops-api-chart.selectorLabels" . | nindent 4 }}
